name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Checkout repository
        uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

 ad7cc6a (Saving local changes before pull)
    - name: Build and Push Docker Image
      run: |
        docker build -t your-dockerhub-username/webapp:latest .
        docker push your-dockerhub-username/webapp:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/webapp
            git pull origin main  # Ensure latest code is fetched
            docker pull tauhid1/webapp:latest
            docker stop webapp || true
            docker rm webapp || true
            docker run -d -p 80:5000 --name webapp tauhid1/webapp:latest
>>>>>>> ad7cc6a (Saving local changes before pull)
